# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         subs-parallel
version:      0.08
version_from: lib/subs/parallel.pm
installdirs:  site
requires:
    Attribute::Handlers:           0
    Exporter:                      0
    Scalar::Util:                  0
    Test::More:                    0
    Test::Simple:                  0
    threads:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
